const express = require('express');
const router = express.Router();
const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require('google-auth-library');

// // spreadsheet url: 
// const sheetUrl = process.env.SHEETS_URL;

// router.post("/", async (req, res) => {
//     const data = req.body;
//     let response = {};
// });

// async function main(name) {
//     // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
//     const serviceAccountAuth = new JWT({
//         // env var values here are copied from service account credentials generated by google
//         // see "Authentication" section in docs for more info
//         email: process.env.SHEETS_EMAIL,
//         key: process.env.SHEETS_KEY,
//         scopes: [
//             'https://www.googleapis.com/auth/spreadsheets',
//         ],
//     });

//     const doc = new GoogleSpreadsheet('1VS0qw5cvPcOhOUp_qvLnwAjLtVw3TJrunubbPihEyZQ', serviceAccountAuth);

//     await doc.loadInfo(); // loads document properties and worksheets

//     console.log("doc.title->", doc.title);

//     // await doc.updateProperties({ title: 'renamed doc' });

//     // const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`

//     // first determine which the name for the new sheet will be
//     let sheets = await doc.sheetsByTitle;

//     let desiredTitle = name;
//     let newTitle = desiredTitle;

//     let counter = 0;

//     while (sheets[newTitle]) {
//         counter++;
//         newTitle = desiredTitle + "-" + counter;
//     }

//     console.log("newTitle will be ->", newTitle);

//     const newSheet = await doc.addSheet({ title: newTitle, headerValues: ['Nationality', 'Equivalent'] });

//     await newSheet.addRows(names);

//     console.log(sheetUrl + "#gid=" + await findSheetId(newTitle, doc));

//     // adding / removing sheets
//     // const newSheet = await doc.addSheet({ title: 'another sheet' });
//     // await newSheet.delete();
// }

// const name = "Alejandro";
// const names = [{ Nationality: "Armenia", Equivalent: "Ale" }, { Nationality: "Italy", Equivalent: "Alessandro" }, { Nationality: "Brasil", Equivalent: "Aleao" }];

// main(name, names);

// async function findSheetId(targetSheet, doc) {
//     let sheets = await doc.sheetsByTitle;
//     return sheets[targetSheet].sheetId;
// }

module.exports = router;